### ISSUE TITLE
Error: Calling ENV.no_optimization is disabled!

### ISSUE THREAD

**Issue by krishnaw14** [osrf/homebrew-ros2#7]
I am getting this: 

`Krishnas-MacBook-Pro:lib krishna$ brew install opensplice
==> Installing opensplice from osrf/ros2
==> Downloading https://github.com/osrf/opensplice/releases/download/6.4.0-0/opensp
Already downloaded: /Users/krishna/Library/Caches/Homebrew/opensplice-6.4.0.tar.gz
==> Patching
patching file src/api/dcps/isocpp/include/dds/pub/AnyDataWriter.hpp
patching file src/api/dcps/isocpp/include/dds/pub/DataWriter.hpp
patching file src/api/dcps/isocpp/include/dds/sub/AnyDataReader.hpp
patching file src/api/dcps/isocpp/include/dds/sub/TDataReader.hpp
patching file src/api/dcps/isocpp/include/dds/topic/AnyTopic.hpp
patching file src/api/dcps/isocpp/include/dds/topic/TTopic.hpp
patching file src/api/dcps/isocpp/include/dds/core/detail/ref_traits.hpp
patching file setup/makefiles/target-only.mak
Hunk #1 succeeded at 234 with fuzz 2.
Error: Calling ENV.no_optimization is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/osrf/homebrew-ros2/opensplice.rb:26:in `install'
Please report this to the osrf/ros2 tap!
Or, even better, submit a PR to fix it!
Krishnas-MacBook-Pro:lib krishna$ talker
dyld: Library not loaded: /usr/local/opt/opensplice/lib/libcmxml.dylib
  Referenced from: /Users/krishna/ros2_install/ros2-osx/bin/talker
  Reason: image not found
Abort trap: 6
Krishnas-MacBook-Pro:lib krishna$ Error: Calling ENV.no_optimization is disabled!`

I am trying to get ros 2 running on my Mac.

**Comment by wjwwood** [comment]
@krishnaw14 our instructions currently advise you to get OpenSplice from their GitHub page, see out binary instructions:

> > If you downloaded a package that includes support for OpenSplice, you will need to install OpenSplice as it is not included in the package itself. Download the latest release from https://github.com/ADLINK-IST/opensplice/releases and unpack it.

> -- https://github.com/ros2/ros2/wiki/OSX-Install-Binary#downloading-ros-2

Or our source build instructions:

> > To install OpenSplice, download the latest release from https://github.com/ADLINK-IST/opensplice/releases and unpack it.
> > ....

> -- https://github.com/ros2/ros2/wiki/OSX-Development-Setup#adlink-opensplice-67

To that end, I'll just remove this formula from this repository rather than fix it.

Thanks for bringing it to our attention though.

**Comment by wjwwood** [comment]
See: 963af5a14e0630d810caf1f69ca4581c7ebf2282
